feat: add multiregional helm jobs

diff --git a/helm-multiregion.yml b/helm-multiregion.yml
--- a/helm-multiregion.yml
+++ b/helm-multiregion.yml
@@ -24,6 +24,51 @@ deploy:production:europe:helm:
           fi
       done
 
+verify:production:europe:
+  extends: .verify
+  stage: verify
+  variables:
+    GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_EUROPE}
+    CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_EUROPE}
+    CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION_EUROPE}
+    NAMESPACE: ${NAMESPACE_PRODUCTION_EUROPE}
+  before_script:
+    - |
+      # CHECK VARIABLES PHASE
+      for var in "GOOGLE_KEY_PRODUCTION_EUROPE" "CLUSTER_NAME_PRODUCTION_EUROPE" "CLUSTER_ZONE_PRODUCTION_EUROPE" "NAMESPACE_PRODUCTION_EUROPE"; do
+          if [ -z "${!var}" ]; then
+            echo "Missing '${var}' variable!"
+            exit 1
+          fi
+      done
+  only:
+    - /^v.+$/i
+  except:
+    - branches
+
+rollback:production:europe:
+  extends: .rollback
+  stage: rollback
+  variables:
+    GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_EUROPE}
+    CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_EUROPE}
+    CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION_EUROPE}
+    NAMESPACE: ${NAMESPACE_PRODUCTION_EUROPE}
+  before_script:
+    - |
+      # CHECK VARIABLES PHASE
+      for var in "GOOGLE_KEY_PRODUCTION_EUROPE" "CLUSTER_NAME_PRODUCTION_EUROPE" "CLUSTER_ZONE_PRODUCTION_EUROPE" "NAMESPACE_PRODUCTION_EUROPE"; do
+          if [ -z "${!var}" ]; then
+            echo "Missing '${var}' variable!"
+            exit 1
+          fi
+      done
+  when: on_failure
+  only:
+    - /^v.+$/i
+  except:
+    - branches
+
 # AMERICA
 deploy:production:america:helm:
   extends: .deploy:production:helm
@@ -47,6 +92,51 @@ deploy:production:america:helm:
           fi
       done
 
+verify:production:america:
+  extends: .verify
+  stage: verify
+  variables:
+    GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_AMERICA}
+    CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_AMERICA}
+    CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION_AMERICA}
+    NAMESPACE: ${NAMESPACE_PRODUCTION_AMERICA}
+  before_script:
+    - |
+      # CHECK VARIABLES PHASE
+      for var in "GOOGLE_KEY_PRODUCTION_AMERICA" "CLUSTER_NAME_PRODUCTION_AMERICA" "CLUSTER_ZONE_PRODUCTION_AMERICA" "NAMESPACE_PRODUCTION_AMERICA"; do
+          if [ -z "${!var}" ]; then
+            echo "Missing '${var}' variable!"
+            exit 1
+          fi
+      done
+  only:
+    - /^v.+$/i
+  except:
+    - branches
+
+rollback:production:america:
+  extends: .rollback
+  stage: rollback
+  variables:
+    GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_AMERICA}
+    CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_AMERICA}
+    CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION_AMERICA}
+    NAMESPACE: ${NAMESPACE_PRODUCTION_AMERICA}
+  before_script:
+    - |
+      # CHECK VARIABLES PHASE
+      for var in "GOOGLE_KEY_PRODUCTION_AMERICA" "CLUSTER_NAME_PRODUCTION_AMERICA" "CLUSTER_ZONE_PRODUCTION_AMERICA" "NAMESPACE_PRODUCTION_AMERICA"; do
+          if [ -z "${!var}" ]; then
+            echo "Missing '${var}' variable!"
+            exit 1
+          fi
+      done
+  when: on_failure
+  only:
+    - /^v.+$/i
+  except:
+    - branches
+
 # ASIA
 deploy:production:asia:helm:
   extends: .deploy:production:helm
@@ -69,3 +159,48 @@ deploy:production:asia:helm:
             exit 1
           fi
       done
+
+verify:production:asia:
+  extends: .verify
+  stage: verify
+  variables:
+    GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_ASIA}
+    CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_ASIA}
+    CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION_ASIA}
+    NAMESPACE: ${NAMESPACE_PRODUCTION_ASIA}
+  before_script:
+    - |
+      # CHECK VARIABLES PHASE
+      for var in "GOOGLE_KEY_PRODUCTION_ASIA" "CLUSTER_NAME_PRODUCTION_ASIA" "CLUSTER_ZONE_PRODUCTION_ASIA" "NAMESPACE_PRODUCTION_ASIA"; do
+          if [ -z "${!var}" ]; then
+            echo "Missing '${var}' variable!"
+            exit 1
+          fi
+      done
+  only:
+    - /^v.+$/i
+  except:
+    - branches
+
+rollback:production:asia:
+  extends: .rollback
+  stage: rollback
+  variables:
+    GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_ASIA}
+    CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_ASIA}
+    CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION_ASIA}
+    NAMESPACE: ${NAMESPACE_PRODUCTION_ASIA}
+  before_script:
+    - |
+      # CHECK VARIABLES PHASE
+      for var in "GOOGLE_KEY_PRODUCTION_ASIA" "CLUSTER_NAME_PRODUCTION_ASIA" "CLUSTER_ZONE_PRODUCTION_ASIA" "NAMESPACE_PRODUCTION_ASIA"; do
+          if [ -z "${!var}" ]; then
+            echo "Missing '${var}' variable!"
+            exit 1
+          fi
+      done
+  when: on_failure
+  only:
+    - /^v.+$/i
+  except:
+    - branches
