chore: cleanup some headers, add check as first thing

diff --git a/helm-branches.yml b/helm-branches.yml
--- a/helm-branches.yml
+++ b/helm-branches.yml
@@ -1,24 +1,32 @@
 deploy:quality:helm:branches:
-  extends: .helm:deploy
   environment:
     name: review/$CI_BUILD_REF_NAME
     url: https://${CI_COMMIT_REF_SLUG}.${DOMAIN_QUALITY}
     on_stop: stop:quality
   variables:
-    CI_COMMIT_TAG: ${CI_COMMIT_SHORT_SHA}
     GOOGLE_KEY: ${GOOGLE_KEY_QUALITY}
     CLUSTER_NAME: ${CLUSTER_NAME_QUALITY}
     CLUSTER_ZONE: ${CLUSTER_ZONE_QUALITY}
-    #SECRET_YAML: ${SECRET_YAML_FEATURE}
     NAMESPACE: ${NAMESPACE_QUALITY}
+    #SECRET_YAML: ${SECRET_YAML_FEATURE}
     ENVIRONMENT: feature
-    APP_NAME: ${CI_COMMIT_REF_SLUG}
+    CI_COMMIT_TAG: ${CI_COMMIT_SHORT_SHA}
   before_script:
+    - |
+      # CHECK VARIABLES PHASE
+      for var in "GOOGLE_KEY_QUALITY" "CLUSTER_NAME_QUALITY" "CLUSTER_ZONE_QUALITY" "NAMESPACE_QUALITY"; do
+          if [ -z "${!var}" ]; then
+            echo "Missing '${var}' variable!"
+            exit 1
+          fi
+      done
+
     - |
       # we need SECRET_YAML_QUALITY to perform DB cloning (it contains quality DB name, SECRET_YAML should contain the new name)
       if [ -n "${SECRET_YAML_QUALITY}" ]; then
         export SECRET_YAML_QUALITY=${SECRET_YAML_QUALITY}
-      fi      
+      fi
+
     - |
       # use a specific CI/CD variable if SECRET_BRANCH is specified in gitlab-ci
       if [ -n "${SECRET_BRANCH}" ]; then
@@ -50,15 +58,7 @@ deploy:quality:helm:branches:
       fi
       export APP_NAME_BRANCH=$( eval echo \$app )
     - echo ${APP_NAME_BRANCH}
-    
-    - |
-      # CHECK VARIABLES PHASE
-      for var in "GOOGLE_KEY_QUALITY" "CLUSTER_NAME_QUALITY" "CLUSTER_ZONE_QUALITY" "NAMESPACE_QUALITY"; do
-          if [ -z "${!var}" ]; then
-            echo "Missing '${var}' variable!"
-            exit 1
-          fi
-      done
+
     - |
       # CLONE DB
       echo "Cloning db"
@@ -109,9 +109,8 @@ deploy:quality:helm:branches:
   except:
     variables:
       - $CI_COMMIT_REF_NAME !~ /^feat/
-  
+
 stop:quality:
-  extends: .stop
   allow_failure: true
   environment:
     name: review/$CI_BUILD_REF_NAME
@@ -128,14 +127,6 @@ stop:quality:
     APP_NAME: ${CI_COMMIT_REF_SLUG}
   before_script:
     - |
-      # use a specific CI/CD variable if SECRET_BRANCH is specified in gitlab-ci
-      if [ -n "${SECRET_BRANCH}" ]; then
-        export SECRET_YAML=${!SECRET_BRANCH}
-      # otherwise, use default SECRET_YAML_FEATURE CI/CD variable
-      else
-        export SECRET_YAML=${SECRET_YAML_FEATURE}
-      fi
-    - |
       # CHECK VARIABLES PHASE
       for var in "GOOGLE_KEY_QUALITY" "CLUSTER_NAME_QUALITY" "CLUSTER_ZONE_QUALITY" "NAMESPACE_QUALITY"; do
           if [ -z "${!var}" ]; then
@@ -143,6 +134,14 @@ stop:quality:
             exit 1
           fi
       done
+    - |
+      # use a specific CI/CD variable if SECRET_BRANCH is specified in gitlab-ci
+      if [ -n "${SECRET_BRANCH}" ]; then
+        export SECRET_YAML=${!SECRET_BRANCH}
+      # otherwise, use default SECRET_YAML_FEATURE CI/CD variable
+      else
+        export SECRET_YAML=${SECRET_YAML_FEATURE}
+      fi
     - |
       # REMOVE DB
       set +e
