feat: add helm testing, follow by rollback on fail

diff --git a/helm-regional.yml b/helm-regional.yml
--- a/helm-regional.yml
+++ b/helm-regional.yml
@@ -15,9 +15,55 @@ deploy:production:helm:
   before_script:
     - |
       # CHECK VARIABLES PHASE
-      for var in "GOOGLE_KEY_PRODUCTION" "CLUSTER_NAME_PRODUCTION" "CLUSTER_ZONE_PRODUCTION"; do
+      for var in "GOOGLE_KEY_PRODUCTION" "CLUSTER_NAME_PRODUCTION" "CLUSTER_ZONE_PRODUCTION" "NAMESPACE_PRODUCTION"; do
           if [ -z "${!var}" ]; then
             echo "Missing '${var}' variable!"
             exit 1
           fi
       done
+
+verify:production:
+  extends: .verify
+  stage: verify
+  variables:
+    GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION}
+    CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION}
+    CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION}
+    NAMESPACE: ${NAMESPACE_PRODUCTION}
+  before_script:
+    - |
+      # CHECK VARIABLES PHASE
+      for var in "GOOGLE_KEY_PRODUCTION" "CLUSTER_NAME_PRODUCTION" "CLUSTER_ZONE_PRODUCTION" "NAMESPACE_PRODUCTION"; do
+          if [ -z "${!var}" ]; then
+            echo "Missing '${var}' variable!"
+            exit 1
+          fi
+      done
+  when: on_failure
+  only:
+    - /^v.+$/i
+  except:
+    - branches
+
+rollback:production:
+  extends: .rollback
+  stage: rollback
+  variables:
+    GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION}
+    CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION}
+    CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION}
+    NAMESPACE: ${NAMESPACE_PRODUCTION}
+  before_script:
+    - |
+      # CHECK VARIABLES PHASE
+      for var in "GOOGLE_KEY_PRODUCTION" "CLUSTER_NAME_PRODUCTION" "CLUSTER_ZONE_PRODUCTION" "NAMESPACE_PRODUCTION"; do
+          if [ -z "${!var}" ]; then
+            echo "Missing '${var}' variable!"
+            exit 1
+          fi
+      done
+  when: on_failure
+  only:
+    - /^v.+$/i
+  except:
+    - branches
