feat: Add Helm-Diff Jobs

diff --git a/helm-multiregion.yml b/helm-multiregion.yml
--- a/helm-multiregion.yml
+++ b/helm-multiregion.yml
@@ -1,9 +1,12 @@
+---
 include:
-  - remote: 'https://raw.githubusercontent.com/jobtome-labs/ci-templates/v3.6.0/helm-quality.yml'
+  - remote: "https://raw.githubusercontent.com/jobtome-labs/ci-templates/feat/helm-diff/helm-quality.yml"
 
 # EUROPE
+
 deploy:production:europe:helm:
   extends: .deploy:production:helm
+
   variables:
     GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_EUROPE}
     CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_EUROPE}
@@ -14,9 +17,12 @@ deploy:production:europe:helm:
     ENVIRONMENT: production
     ENVIRONMENT_NAME: production-europe
     ENVIRONMENT_PATH: ${ENVIRONMENT_PATH_EUROPE}
+
   before_script:
     - |
+
       # CHECK VARIABLES PHASE
+
       for var in "GOOGLE_KEY_PRODUCTION_EUROPE" "CLUSTER_NAME_PRODUCTION_EUROPE" "CLUSTER_ZONE_PRODUCTION_EUROPE"; do
           if [ -z "${!var}" ]; then
             echo "Missing '${var}' variable!"
@@ -26,29 +32,66 @@ deploy:production:europe:helm:
 
 verify:production:europe:
   extends: .verify
+
   stage: verify
+
   variables:
     GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_EUROPE}
     CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_EUROPE}
     CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION_EUROPE}
     NAMESPACE: ${NAMESPACE_PRODUCTION_EUROPE}
+
   before_script:
     - |
+
       # CHECK VARIABLES PHASE
+
       for var in "GOOGLE_KEY_PRODUCTION_EUROPE" "CLUSTER_NAME_PRODUCTION_EUROPE" "CLUSTER_ZONE_PRODUCTION_EUROPE" "NAMESPACE_PRODUCTION_EUROPE"; do
           if [ -z "${!var}" ]; then
             echo "Missing '${var}' variable!"
             exit 1
           fi
       done
+
   only:
     - /^v.+$/i
   except:
     - branches
 
+helm:diff:production:europe:
+  extends: .helm:diff
+
+  variables:
+    GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_EUROPE}
+    CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_EUROPE}
+    CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION_EUROPE}
+    DOMAIN: ${DOMAIN_PRODUCTION_EUROPE}
+    SECRET_YAML: ${SECRET_YAML_PRODUCTION_EUROPE}
+    NAMESPACE: ${NAMESPACE_PRODUCTION_EUROPE}
+    ENVIRONMENT: production
+    ENVIRONMENT_NAME: production-europe
+    ENVIRONMENT_PATH: ${ENVIRONMENT_PATH_EUROPE}
+
+  before_script:
+    - |
+
+      # CHECK VARIABLES PHASE
+
+      for var in "GOOGLE_KEY_PRODUCTION_EUROPE" "CLUSTER_NAME_PRODUCTION_EUROPE" "CLUSTER_ZONE_PRODUCTION_EUROPE"; do
+        if [ -z "${!var}" ]; then
+          echo "Missing '${var}' Variable!"
+          exit 1
+        fi
+      done
+
+  rules:
+    - if: '$ENABLE_HELM_DIFF == "true" && $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
+
 # AMERICA
+
 deploy:production:america:helm:
   extends: .deploy:production:helm
+
   variables:
     GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_AMERICA}
     CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_AMERICA}
@@ -59,9 +102,12 @@ deploy:production:america:helm:
     ENVIRONMENT: production
     ENVIRONMENT_NAME: production-america
     ENVIRONMENT_PATH: ${ENVIRONMENT_PATH_AMERICA}
+
   before_script:
     - |
+
       # CHECK VARIABLES PHASE
+
       for var in "GOOGLE_KEY_PRODUCTION_AMERICA" "CLUSTER_NAME_PRODUCTION_AMERICA" "CLUSTER_ZONE_PRODUCTION_AMERICA"; do
           if [ -z "${!var}" ]; then
             echo "Missing '${var}' variable!"
@@ -71,29 +117,66 @@ deploy:production:america:helm:
 
 verify:production:america:
   extends: .verify
+
   stage: verify
+
   variables:
     GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_AMERICA}
     CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_AMERICA}
     CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION_AMERICA}
     NAMESPACE: ${NAMESPACE_PRODUCTION_AMERICA}
+
   before_script:
     - |
+
       # CHECK VARIABLES PHASE
+
       for var in "GOOGLE_KEY_PRODUCTION_AMERICA" "CLUSTER_NAME_PRODUCTION_AMERICA" "CLUSTER_ZONE_PRODUCTION_AMERICA" "NAMESPACE_PRODUCTION_AMERICA"; do
           if [ -z "${!var}" ]; then
             echo "Missing '${var}' variable!"
             exit 1
           fi
       done
+
   only:
     - /^v.+$/i
   except:
     - branches
 
+helm:diff:production:america:
+  extends: .helm:diff
+
+  variables:
+    GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_AMERICA}
+    CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_AMERICA}
+    CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION_AMERICA}
+    DOMAIN: ${DOMAIN_PRODUCTION_AMERICA}
+    SECRET_YAML: ${SECRET_YAML_PRODUCTION_AMERICA}
+    NAMESPACE: ${NAMESPACE_PRODUCTION_AMERICA}
+    ENVIRONMENT: production
+    ENVIRONMENT_NAME: production-america
+    ENVIRONMENT_PATH: ${ENVIRONMENT_PATH_AMERICA}
+
+  before_script:
+    - |
+
+      # CHECK VARIABLES PHASE
+
+      for var in "GOOGLE_KEY_PRODUCTION_AMERICA" "CLUSTER_NAME_PRODUCTION_AMERICA" "CLUSTER_ZONE_PRODUCTION_AMERICA"; do
+        if [ -z "${!var}" ]; then
+          echo "Missing '${var}' Variable!"
+          exit 1
+        fi
+      done
+
+  rules:
+    - if: '$ENABLE_HELM_DIFF == "true" && $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
+
 # ASIA
+
 deploy:production:asia:helm:
   extends: .deploy:production:helm
+
   variables:
     GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_ASIA}
     CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_ASIA}
@@ -104,9 +187,12 @@ deploy:production:asia:helm:
     ENVIRONMENT: production
     ENVIRONMENT_NAME: production-asia
     ENVIRONMENT_PATH: ${ENVIRONMENT_PATH_ASIA}
+
   before_script:
     - |
+
       # CHECK VARIABLES PHASE
+
       for var in "GOOGLE_KEY_PRODUCTION_ASIA" "CLUSTER_NAME_PRODUCTION_ASIA" "CLUSTER_ZONE_PRODUCTION_ASIA"; do
           if [ -z "${!var}" ]; then
             echo "Missing '${var}' variable!"
@@ -116,22 +202,57 @@ deploy:production:asia:helm:
 
 verify:production:asia:
   extends: .verify
+
   stage: verify
+
   variables:
     GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_ASIA}
     CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_ASIA}
     CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION_ASIA}
     NAMESPACE: ${NAMESPACE_PRODUCTION_ASIA}
+
   before_script:
     - |
+
       # CHECK VARIABLES PHASE
+
       for var in "GOOGLE_KEY_PRODUCTION_ASIA" "CLUSTER_NAME_PRODUCTION_ASIA" "CLUSTER_ZONE_PRODUCTION_ASIA" "NAMESPACE_PRODUCTION_ASIA"; do
           if [ -z "${!var}" ]; then
             echo "Missing '${var}' variable!"
             exit 1
           fi
       done
+
   only:
     - /^v.+$/i
   except:
     - branches
+
+helm:diff:production:asia:
+  extends: .helm:diff
+
+  variables:
+    GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION_ASIA}
+    CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION_ASIA}
+    CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION_ASIA}
+    DOMAIN: ${DOMAIN_PRODUCTION_ASIA}
+    SECRET_YAML: ${SECRET_YAML_PRODUCTION_ASIA}
+    NAMESPACE: ${NAMESPACE_PRODUCTION_ASIA}
+    ENVIRONMENT: production
+    ENVIRONMENT_NAME: production-asia
+    ENVIRONMENT_PATH: ${ENVIRONMENT_PATH_ASIA}
+
+  before_script:
+    - |
+
+      # CHECK VARIABLES PHASE
+
+      for var in "GOOGLE_KEY_PRODUCTION_ASIA" "CLUSTER_NAME_PRODUCTION_ASIA" "CLUSTER_ZONE_PRODUCTION_ASIA"; do
+        if [ -z "${!var}" ]; then
+          echo "Missing '${var}' Variable!"
+          exit 1
+        fi
+      done
+
+  rules:
+    - if: '$ENABLE_HELM_DIFF == "true" && $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
diff --git a/helm-regional.yml b/helm-regional.yml
--- a/helm-regional.yml
+++ b/helm-regional.yml
@@ -1,8 +1,10 @@
+---
 include:
-  - remote: 'https://raw.githubusercontent.com/jobtome-labs/ci-templates/v3.6.0/helm-quality.yml'
+  - remote: "https://raw.githubusercontent.com/jobtome-labs/ci-templates/feat/helm-diff/helm-quality.yml"
 
 deploy:production:helm:
   extends: .deploy:production:helm
+
   variables:
     GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION}
     CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION}
@@ -12,9 +14,12 @@ deploy:production:helm:
     NAMESPACE: ${NAMESPACE_PRODUCTION}
     ENVIRONMENT: production
     ENVIRONMENT_NAME: production
+
   before_script:
     - |
+
       # CHECK VARIABLES PHASE
+
       for var in "GOOGLE_KEY_PRODUCTION" "CLUSTER_NAME_PRODUCTION" "CLUSTER_ZONE_PRODUCTION" "NAMESPACE_PRODUCTION" "DOMAIN_PRODUCTION"; do
           if [ -z "${!var}" ]; then
             echo "Missing '${var}' variable!"
@@ -24,22 +29,56 @@ deploy:production:helm:
 
 verify:production:
   extends: .verify
+
   stage: verify
+
   variables:
     GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION}
     CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION}
     CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION}
     NAMESPACE: ${NAMESPACE_PRODUCTION}
+
   before_script:
     - |
+
       # CHECK VARIABLES PHASE
+
       for var in "GOOGLE_KEY_PRODUCTION" "CLUSTER_NAME_PRODUCTION" "CLUSTER_ZONE_PRODUCTION" "NAMESPACE_PRODUCTION"; do
           if [ -z "${!var}" ]; then
             echo "Missing '${var}' variable!"
             exit 1
           fi
       done
+
   only:
     - /^v.+$/i
   except:
     - branches
+
+helm:diff:production:
+  extends: .helm:diff
+
+  variables:
+    GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION}
+    CLUSTER_NAME: ${CLUSTER_NAME_PRODUCTION}
+    CLUSTER_ZONE: ${CLUSTER_ZONE_PRODUCTION}
+    DOMAIN: ${DOMAIN_PRODUCTION}
+    SECRET_YAML: ${SECRET_YAML_PRODUCTION}
+    NAMESPACE: ${NAMESPACE_PRODUCTION}
+    ENVIRONMENT: production
+    ENVIRONMENT_NAME: production
+
+  before_script:
+    - |
+
+      # CHECK VARIABLES PHASE
+
+      for var in "GOOGLE_KEY_PRODUCTION" "CLUSTER_NAME_PRODUCTION" "CLUSTER_ZONE_PRODUCTION" "NAMESPACE_PRODUCTION" "DOMAIN_PRODUCTION"; do
+        if [ -z "${!var}" ]; then
+          echo "Missing '${var}' Variable!"
+          exit 1
+        fi
+      done
+
+  rules:
+    - if: '$ENABLE_HELM_DIFF == "true" && $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
