added golint

diff --git a/lint-go.yml b/lint-go.yml
--- a/lint-go.yml
+++ b/lint-go.yml
@@ -1,14 +1,34 @@
 lint:go:
   stage: lint
-  image: cytopia/golint:latest-release-0.1
+  image: gadiener/golint-reviewdog:v1.0.0
+  variables:
+    GITLAB_API: ${CI_API_V4_URL}
   script:
     - |
-
       echo
       echo "-> Linting code:"
       echo
 
-      golint .
+      if [ -z "${LINT_PATH}" ]; then
+        LINT_PATH="./..."
+      fi
+
+      if [ "${ENABLE_REVIEWDOG}" = "1" ]; then
+        echo
+        echo "-> Enabled Review Dog!"
+        echo
+
+        if [ -z "${REVIEWDOG_GITLAB_API_TOKEN}" ]; then
+          echo
+          echo "-> [WARNING] Missing 'REVIEWDOG_GITLAB_API_TOKEN' variable!"
+          echo
+          exit 1
+        fi
+
+        golint "${LINT_PATH}" | reviewdog -f=golint -diff="git diff master" -reporter=gitlab-mr-discussion
+      else
+        golint "${LINT_PATH}"
+      fi
 
       echo
       echo "-> Code checked!"
