improved serverless stages

diff --git a/serverless-regional.yml b/serverless-regional.yml
--- a/serverless-regional.yml
+++ b/serverless-regional.yml
@@ -1,7 +1,26 @@
 include:
-  - remote: 'https://raw.githubusercontent.com/jobtome-labs/ci-templates/v2.2.4/templates/serverless.yml'
+  - remote: 'https://raw.githubusercontent.com/jobtome-labs/ci-templates/v2.3.0/serverless-quality.yml'
 
 deploy:production:
   extends: .serverless:deploy
   variables:
+    GOOGLE_KEY: ${GOOGLE_KEY_PRODUCTION}
+    REGION: ${REGION_PRODUCTION}
+    DOMAIN: ${DOMAIN_PRODUCTION}
+    SECRET_YAML: ${SECRET_YAML_PRODUCTION}
+    SECRET_ENV_LIST: ${SECRET_ENV_LIST_PRODUCTION}
+    TRIGGER_TOPIC: ${TRIGGER_TOPIC_PRODUCTION}
     ENVIRONMENT: production
+  before_script:
+    - |
+      # CHECK VARIABLES PHASE
+      for var in "GOOGLE_KEY_PRODUCTION" "REGION_PRODUCTION"; do
+          if [ -z "${!var}" ]; then
+            echo "Missing '${var}' variable!"
+            exit 1
+          fi
+      done
+  only:
+    - /^v.+$/i
+  except:
+    - branches
